name: Hello World Python

on:
  push:
    branches:
      - main

  schedule:
    - cron: '* * * * *'  # Runs every minute
    
jobs:
  run-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run hello_world.py
        run: python hello_world.py
